theme: jekyll-theme-minimal
logo: transpose-publishing.github.io/images/TRANSPOSElogo.png
title: TRANSPOSE
description: TRANsparency in Scholarly Publishing for Open Scholarship Evolution
twitter_username: TRANSPOSEsci
